name: Sync Fork

on:
  issues:
    types: [opened]

jobs:
  sync:
    if: github.event.issue.title == 'SyncFork'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.PAT }}

    - name: Configure Git
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"

    - name: Sync fork
      run: |
        git remote add upstream https://github.com/microsoft/vscode.git
        git fetch upstream
        git checkout main
        git merge --allow-unrelated-histories --strategy-option ours upstream/main
        git push
